apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # You can choose any port in the range 30000-32767
  type: NodePort
