apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: NodePort
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 80         # Port on the service
      targetPort: 8081 # Port on the container
      nodePort: 30001  # NodePort to access the service
